highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "多看一二"
#name: "薛定谔の喵"
#markdown: rdiscount
markdown: kramdown

author: "fuhu"
atom-baseurl: "https://fuhu.me"
#disqus: "duokanyier"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-instagram
    href: https://www.instagram.com/hfu.cn/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

